steps:
  # Build image with Kaniko
  - name: 'gcr.io/kaniko-project/executor:v1.23.2'
    args:
      - --dockerfile=Dockerfile
      - --context=dir://.
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/natacha/natacha-api:$BUILD_ID
      - --cache=false

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:467.0.0'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud run deploy natacha-api \
          --region us-central1 \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/natacha/natacha-api:$BUILD_ID \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
