steps:
  - name: 'gcr.io/kaniko-project/executor:v1.23.2'
    args:
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/natacha/natacha-api:$BUILD_ID
      - --cache=false
      - --use-new-run
      - --snapshotMode=time
      - --dockerfile=Dockerfile

options:
  logging: CLOUD_LOGGING_ONLY
