# cloudbuild.yaml · baseline reproducible para Cloud Run
timeout: "1200s"

substitutions:
  _SERVICE: "natacha-api"
  _REGION: "us-central1"
  _PROJECT: "asistente-sebastian"
  _DOCKER_IMAGE: "natacha-api"
  _REPO: "natacha"
  _PLATFORM: "managed"
  _CPU: "1"
  _MEM: "512Mi"
  _CONCURRENCY: "80"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "4"
  _ALLOW_UNAUTH: "false"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  substitutionOption: ALLOW_LOOSE

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args: ["build", "-f", "Dockerfile", "-t", "us-central1-docker.pkg.dev/${_PROJECT}/${_REPO}/${_DOCKER_IMAGE}:${BUILD_ID}", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args: ["push", "us-central1-docker.pkg.dev/${_PROJECT}/${_REPO}/${_DOCKER_IMAGE}:${BUILD_ID}"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Deploy to Cloud Run"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -euo pipefail
        gcloud run deploy ${_SERVICE} \
          --project ${_PROJECT} \
          --region ${_REGION} \
          --platform ${_PLATFORM} \
          --image us-central1-docker.pkg.dev/${_PROJECT}/${_REPO}/${_DOCKER_IMAGE}:${BUILD_ID} \
          --cpu ${_CPU} \
          --memory ${_MEM} \
          --concurrency ${_CONCURRENCY} \
          --min-instances ${_MIN_INSTANCES} \
          --max-instances ${_MAX_INSTANCES} \
          --port 8080 \
          --quiet

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "Traffic split (stable 80 / latest 20)"
    entrypoint: bash
    args:
      - "-c"
      - |
        set -euo pipefail
        CURRENT_STABLE=$(gcloud run services describe ${_SERVICE} --project ${_PROJECT} --region ${_REGION} --format="value(status.traffic.percent,status.traffic.revisionName)" | awk '$1==80{print $2}' || true)
        if [[ -n "$$CURRENT_STABLE" ]]; then
          gcloud run services update-traffic ${_SERVICE} \
            --project ${_PROJECT} --region ${_REGION} \
            --to-revisions $$CURRENT_STABLE=80,LATEST=20
        else
          gcloud run services update-traffic ${_SERVICE} \
            --project ${_PROJECT} --region ${_REGION} \
            --to-latest
        fi

images:
  - "us-central1-docker.pkg.dev/${_PROJECT}/${_REPO}/${_DOCKER_IMAGE}:${BUILD_ID}"
