apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://natacha-memory-console-422255208682.us-central1.run.app","https://natacha-memory-console-mkwskljrhq-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: natacha-memory-console
  namespace: '422255208682'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 544.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: kmsxpwdeqa
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: MEM_CONSOLE_TOKEN
          value: super-secret-token
        image: us-central1-docker.pkg.dev/asistente-sebastian/natacha-repo/memory_console:v1-20251106-045842-1e3f487
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: natacha-memory-console@asistente-sebastian.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
