# Imagen base ligera de Python
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential nano && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir fastapi uvicorn[standard] python-dotenv watchdog

COPY . .

EXPOSE 8080

# 👇 unificamos con la app real
CMD ["uvicorn", "natacha_app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
